#:schema https://raw.githubusercontent.com/lapce/lapce/master/extra/schemas/color-theme.json
[color-theme]
name = "Tokyo Night Storm"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
white = "#c0caf5"
black = "#414868"
grey = "#9aa5ce"
blue = "#7aa2f7"
red = "#f7768e"
yellow = "#e0af68"
orange = "#ebbcba"
green = "#73daca"
purple = "#e0def4"
cyan = "#7dcfff"
magenta = "#bb9af7"

[color-theme.syntax]
"comment" = "#565f89"
# "boolean" = "#ff9e64"
"constant" = "#ff9e64"
"type" = "#9ccfd8"
"typeAlias" = "#9ccfd8"
"number" = "#ff9e64"
"enum" = "$yellow"
"struct" = "$white"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$magneta"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable" = "$white"
"variable.other.member" = "$red"
"string" = "#9ece6a"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"
# "exception" = "$blue"
# "repeat" = "$magenta"
# "conditional" = "$blue"
# "punctuation.bracket" = "$red"
"punctuation.delimiter" = "$red"
# "punctuation.special" = "$blue"
# "field" = "$green"
# "parameter" = "$red"
# "text.literal" = "$red"
"text.uri" = "$red"
"text.reference" = "$red"
"string.escape" = "$red"
# "string.special" = "$green"
# "constant.builtin" = "$blue"
# "function.builtin" = "$blue"
"tag" = "$blue"
# "variable.builtin" = "$blue"
# "variable.parameter" = "$blue"
# "namespace" = "$blue"
# "keyword.control" = "$blue"
# "keyword.control.import" = "$blue"
# "keyword.storage.type" = "#ff9e64"
# "keyword.storage.modifier" = "$blue"

[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#1f1d2e"
"lapce.border" = "#1f1d2e"
"lapce.scroll_bar" = "$grey"

"lapce.button.primary.background" = "#3d59a1dd"
"lapce.button.primary.foreground" = "#ffffff"

# tab
"lapce.tab.active.background" = "#24283b"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#528BFF"

"lapce.tab.inactive.background" = "#24283b"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#528BFF77"

"lapce.tab.separator" = ""

"lapce.remote.icon" = "$black"
"lapce.remote.local" = "#4078F2"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$white"
"lapce.plugin.author" = "#B0B0B0"

"editor.background" = "#24283b" # base
"editor.foreground" = "#a9b1d6"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#528BFF"
"editor.selection" = "#403d52"
"editor.current_line" = "#21202e"
"editor.link" = "$magneta"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$black"

"inlay_hint.foreground" = "$white"
"inlay_hint.background" = "#524f6788"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E06C7520"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.other.foreground" = "#5C6370"
"error_lens.other.background" = "#5C637020"

"source_control.added" = "#73daca32"
"source_control.removed" = "#f7768e32"
"source_control.modified" = "#7aa2f732"

"palette.background" = "#24283b"
"palette.foreground" = "$white"
"palette.current.background" = "#30374b"
"palette.current.foreground" = "$white"

"completion.background" = "#24283b"
"completion.current" = "#30374b"

"hover.background" = "#24283b"

"activity.background" = "#24283b"
"activity.current" = "#30374b"

"panel.background" = "#24283b"
"panel.foreground" = "#787c99"
"panel.foreground.dim" = "#30374b"
"panel.current.background" = "#1a1b26"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#30374b"
"panel.hovered.background" = "#1f1d2e"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#30374b"

"status.background" = "#1a1b26"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"
"status.foreground" = "$white"

"markdown.blockquote" = "#9aa5ce"

"terminal.cursor" = "$white"
"terminal.foreground" = "$white"
"terminal.background" = "#24283b"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$white"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$black"
